In [1]:
import numpy as np
import pandas as pd

# Features and usage of Numpy library

---

In [2]:
# NumPy array:
# It is the basic data structure of the NumPy library and can be defined as an n-dimensional array.
# All elements are of the same data type.
# It is specifically designed for efficient mathematical operations when working with large and complex datasets.
# It is faster than Python lists because they are optimized in C and use memory more efficiently.

In [3]:
first_list=[1,2,3,4]
first_array=np.array(first_list)
print(type(first_array))
print(first_array)

<class 'numpy.ndarray'>
[1 2 3 4]

In [4]:
second_list=[5,6,7,8]
second_array=np.array([first_list,second_list])
second_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
second_array.shape

(2, 4)

In [6]:
np.zeros(10, dtype=int)
# one dimensional array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((4,5))
# multidimensional array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.identity(n=6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [10]:
np.arange(0,40,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
td=np.random.randint(0,20,(4,4))
td

array([[10,  6,  9,  8],
       [ 7,  4,  5,  3],
       [10, 12,  0,  9],
       [18,  1,  1,  4]])

In [13]:
td[1:,2:]

array([[5, 3],
       [0, 9],
       [1, 4]])

In [14]:
td[::-1,::-1]

array([[ 4,  1,  1, 18],
       [ 9,  0, 12, 10],
       [ 3,  5,  4,  7],
       [ 8,  9,  6, 10]])

In [15]:
np.random.normal(0,1,(3,3))
# (mean,standart deviation, size)

array([[ 0.8799974 ,  1.66288996, -1.30502526],
       [-0.70980364, -0.1102911 ,  0.81034256],
       [-1.51630911, -1.00624719, -0.35402874]])

In [16]:
# array properties
x=np.random.randint(20, size=10)
x

array([19,  4,  7,  7, 19, 10,  9,  8,  2,  0])

In [17]:
print(x.ndim) # number of dimensions
print(x.shape) # dimension information
print(x.size) # total number of elements
print(x.dtype)

1
(10,)
10
int64

In [18]:
# array reshaping
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b=a.reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b.ndim

2

In [21]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
# array concatenation
x=np.array([1,2,3])
y= np.array([4,5,6])
z= np.array([7,8,9])

In [24]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
q=np.array([[1,2,3],
           [7,8,9]])

In [26]:
np.concatenate([q,q], axis=0)

array([[1, 2, 3],
       [7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])

In [27]:
np.concatenate([q,q], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [7, 8, 9, 7, 8, 9]])

In [28]:
# array splitting

In [29]:
# one-dimensional separation
d1=np.array([0,0,0,0,11,11,11,7,8,9])

In [30]:
np.split(d1,[4,7])

[array([0, 0, 0, 0]), array([11, 11, 11]), array([7, 8, 9])]

In [31]:
a,b,c=np.split(d1,[4,7])
b

array([11, 11, 11])

In [32]:
# two-dimensional separation
k=np.arange(20).reshape(4,5)
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
first,second=np.vsplit(k,[2])
print(first)
print(second)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]

In [34]:
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
np.hsplit(k,[2])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

In [36]:
# sorting

In [37]:
z=np.array([5,8,4,9,13,1,5,6])
np.sort(z)

array([ 1,  4,  5,  5,  6,  8,  9, 13])

In [38]:
m=np.random.normal(10,5,(3,3))
m

array([[ 9.88967689, 18.9934801 , 15.16486619],
       [16.80447509, 11.69402825,  1.28001056],
       [23.87025186,  4.14603005,  6.8448422 ]])

In [39]:
np.sort(m, axis=1) # Sort rows

array([[ 9.88967689, 15.16486619, 18.9934801 ],
       [ 1.28001056, 11.69402825, 16.80447509],
       [ 4.14603005,  6.8448422 , 23.87025186]])

In [40]:
np.sort(m, axis=0) # Sort columns

array([[ 9.88967689,  4.14603005,  1.28001056],
       [16.80447509, 11.69402825,  6.8448422 ],
       [23.87025186, 18.9934801 , 15.16486619]])

In [41]:
# accessing elements with index
k= np.random.randint(20, size=10)
k

array([ 1, 19,  3,  6, 10,  0, 13,  5,  7,  2])

In [42]:
print(k[0])
print(k[-1])
print(k[2:6])
print(k[0:3])
print(k[:5])

1
2
[ 3  6 10  0]
[ 1 19  3]
[ 1 19  3  6 10]

In [43]:
print(k[0::2])
print(k[0:10:5])
print(k[::-1])

[ 1  3 10 13  7]
[1 0]
[ 2  7  5 13  0 10  6  3 19  1]

In [44]:
k[2]=7
k

array([ 1, 19,  7,  6, 10,  0, 13,  5,  7,  2])

In [45]:
np.random.seed(42)
m= np.random.randint(20, size=(4,6))
m

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11],
       [11, 16,  9, 15, 14, 14]])

In [46]:
m[3,1]

16

In [47]:
m[:,:]

array([[ 6, 19, 14, 10,  7,  6],
       [18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11],
       [11, 16,  9, 15, 14, 14]])

In [48]:
m[:,0]

array([ 6, 18,  1, 11])

In [49]:
m[0,:]

array([ 6, 19, 14, 10,  7,  6])

In [50]:
m[0:2, 0:3]

array([[ 6, 19, 14],
       [18, 10, 10]])

In [51]:
m[1:3,:]

array([[18, 10, 10,  3,  7,  2],
       [ 1, 11,  5,  1,  0, 11]])

In [52]:
# copy method: It separates the selected subset from the main set. Thus, changes made to the subset do not affect the main set.

In [53]:
h=np.random.randint(10,size =(5,5))
h

array([[2, 6, 3, 8, 2],
       [4, 2, 6, 4, 8],
       [6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0]])

In [54]:
alt_h=h[0:3,0:4].copy()
alt_h

array([[2, 6, 3, 8],
       [4, 2, 6, 4],
       [6, 1, 3, 8]])

In [55]:
alt_h[0,0]=777
alt_h[2,3]=111

In [56]:
alt_h

array([[777,   6,   3,   8],
       [  4,   2,   6,   4],
       [  6,   1,   3, 111]])

In [57]:
h

array([[2, 6, 3, 8, 2],
       [4, 2, 6, 4, 8],
       [6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0]])

In [58]:
#fancy index: It is a method of indexing specific elements in an array using index structures such as a list or array.

In [59]:
g=np.arange(0,40,5)
g

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [60]:
get_it=[0,3,4,6]

In [61]:
g[get_it]

array([ 0, 15, 20, 30])

In [62]:
g[ 20 > g ]

array([ 0,  5, 10, 15])

In [63]:
g[g == 4]

array([], dtype=int64)

In [64]:
g [(g != 10) & (g %2 == 0)]

array([ 0, 20, 30])

In [65]:
f=np.arange(16).reshape((4,4))
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
x=np.array([0,2])
y=np.array([2,3])

In [67]:
f[x,y]

array([ 2, 11])

In [68]:
#fancy with slice
f[0:,y]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [69]:
f[x,:2]

array([[0, 1],
       [8, 9]])

In [70]:
# mathematical operations

In [71]:
p=np.array([1,2,3,4,5,6,7])

In [72]:
np.subtract(p,1) # -

array([0, 1, 2, 3, 4, 5, 6])

In [73]:
np.add(p,1) # +

array([2, 3, 4, 5, 6, 7, 8])

In [74]:
np.multiply(p,3) # *

array([ 3,  6,  9, 12, 15, 18, 21])

In [75]:
np.divide(p,2) # /

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [76]:
np.power(p,3) # üs alma

array([  1,   8,  27,  64, 125, 216, 343])

In [77]:
np.mod(p,2)

array([1, 0, 1, 0, 1, 0, 1])

In [78]:
np.log(p)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [79]:
np.sqrt(p)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [80]:
second_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
second_array + second_array

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [82]:
second_array * second_array

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [83]:
second_array ** second_array

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]])

# Features and usage of Pandas library

---

In [84]:
# used for data analysis and data manipulation
# series: It is the basic one-dimensional data structure of the Pandas library. May consist of a list or a dictionary.
# dataFrame: It is the basic two-dimensional data structure of the Pandas library. It consists of rows and columns.

In [85]:
#series
d = pd.Series([10,20,30,40,50,60])
d

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [86]:
print(type(d))

<class 'pandas.core.series.Series'>

In [87]:
print(d.axes)
print(d.size)
print(d.ndim)
print(d.values)

[RangeIndex(start=0, stop=6, step=1)]
6
1
[10 20 30 40 50 60]

In [88]:
d.head() # Get the first 5 elements

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [89]:
d.tail() # get the last 5 elemants

1    20
2    30
3    40
4    50
5    60
dtype: int64

In [90]:
d[0:2]

0    10
1    20
dtype: int64

In [91]:
n=pd.Series([1,2,3], index=["first","second","third"])
n

first     1
second    2
third     3
dtype: int64

In [92]:
n["second"]

2

In [93]:
f=pd.concat([d,n])
f

0         10
1         20
2         30
3         40
4         50
5         60
first      1
second     2
third      3
dtype: int64

In [94]:
print(f.index)

Index([0, 1, 2, 3, 4, 5, 'first', 'second', 'third'], dtype='object')

In [95]:
print(f.keys)

<bound method Series.keys of 0         10
1         20
2         30
3         40
4         50
5         60
first      1
second     2
third      3
dtype: int64>

In [96]:
list(f.items())

[(0, 10),
 (1, 20),
 (2, 30),
 (3, 40),
 (4, 50),
 (5, 60),
 ('first', 1),
 ('second', 2),
 ('third', 3)]

In [97]:
"first" in f

True

In [98]:
f[[2,3]]

2    30
3    40
dtype: int64

In [99]:
first_dict={"x":5,"y":10,"z":15}
pd.Series(first_dict)

x     5
y    10
z    15
dtype: int64

In [100]:
# DATAFRAME

In [101]:
l=["a","b","c","d","e"]
pd.DataFrame(l, columns=["harfler"])

  harfler
0       a
1       b
2       c
3       d
4       e

In [102]:
z=np.arange(1,17).reshape((4,4))
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [103]:
df=pd.DataFrame(z, columns= ["var1", "var2","var3","var4"])
df

   var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16

In [104]:
df.columns=("v1","v2","v3","v4")
df

   v1  v2  v3  v4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [105]:
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['v1', 'v2', 'v3', 'v4'], dtype='object')]

In [106]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [107]:
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [108]:
type(df.values)

numpy.ndarray

In [109]:
d1=np.random.randint(15, size=5)
d2=np.random.randint(15, size=5)
d3=np.random.randint(15, size=5)

In [110]:
dc={"first": d1,"second": d2, "third": d3}
dc

{'first': array([3, 1, 7, 3, 1]),
 'second': array([13,  5,  5,  9,  3]),
 'third': array([ 5, 12, 14,  1,  9])}

In [111]:
df1=pd.DataFrame(dc)
df1

   first  second  third
0      3      13      5
1      1       5     12
2      7       5     14
3      3       9      1
4      1       3      9

In [112]:
df1[0:3]

   first  second  third
0      3      13      5
1      1       5     12
2      7       5     14

In [113]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [114]:
df1.index="a","b","c","d","e"
df1

   first  second  third
a      3      13      5
b      1       5     12
c      7       5     14
d      3       9      1
e      1       3      9

In [115]:
df1["a":"c"]

   first  second  third
a      3      13      5
b      1       5     12
c      7       5     14

In [116]:
df1.drop("b",axis=0)
# If we want to permanently delete any row, we add "inplace=true"

   first  second  third
a      3      13      5
c      7       5     14
d      3       9      1
e      1       3      9

In [117]:
df1

   first  second  third
a      3      13      5
b      1       5     12
c      7       5     14
d      3       9      1
e      1       3      9

In [118]:
l=["first", "sixth","second"]

for i in l:
  print(i in df1)

True
False
True

In [119]:
df1["fifth"]=df1["first"]*df1["second"]
df1

   first  second  third  fifth
a      3      13      5     39
b      1       5     12      5
c      7       5     14     35
d      3       9      1     27
e      1       3      9      3

In [120]:
df1.drop("fifth", axis=1, inplace=True)
df1

   first  second  third
a      3      13      5
b      1       5     12
c      7       5     14
d      3       9      1
e      1       3      9

In [121]:
df1.shape

(5, 3)

In [122]:
df1['second'].mean()

7.0

In [123]:
df1.describe().T

        count  mean       std  min  25%  50%   75%   max
first     5.0   3.0  2.449490  1.0  1.0  3.0   3.0   7.0
second    5.0   7.0  4.000000  3.0  5.0  5.0   9.0  13.0
third     5.0   8.2  5.263079  1.0  5.0  9.0  12.0  14.0

In [124]:
# loc[]: Uses labels (row/column names) for selection.

In [125]:
# iloc[]: Uses integer positions (row/column index numbers).

In [126]:
df2=np.random.randint(1,20, size=(5,4))
clmns=["a","b","c","d"]
df2=pd.DataFrame(df2,columns=clmns)
df2

    a   b   c   d
0  12   2  10   4
1  14  16  15   8
2  14   8  16  13
3  18  15  13   9
4  15  13   1   7

In [127]:
df2.loc[0:3]

    a   b   c   d
0  12   2  10   4
1  14  16  15   8
2  14   8  16  13
3  18  15  13   9

In [128]:
df2.iloc[0:3]

    a   b   c   d
0  12   2  10   4
1  14  16  15   8
2  14   8  16  13

In [129]:
df2.iloc[1,0]

14

In [130]:
df2.loc[0:2, "b"]

0     2
1    16
2     8
Name: b, dtype: int64

In [131]:
df2.iloc[0:3]["b"]

0     2
1    16
2     8
Name: b, dtype: int64

In [132]:
df2

    a   b   c   d
0  12   2  10   4
1  14  16  15   8
2  14   8  16  13
3  18  15  13   9
4  15  13   1   7

In [133]:
df2[df2.a > 10][["b","d"]]

    b   d
0   2   4
1  16   8
2   8  13
3  15   9
4  13   7

In [134]:
df2.loc[(df2.a < 10),["c"]]

Empty DataFrame
Columns: [c]
Index: []

In [135]:
#concat
df3=df2*50
df3

     a    b    c    d
0  600  100  500  200
1  700  800  750  400
2  700  400  800  650
3  900  750  650  450
4  750  650   50  350

In [136]:
df2

    a   b   c   d
0  12   2  10   4
1  14  16  15   8
2  14   8  16  13
3  18  15  13   9
4  15  13   1   7

In [137]:
pd.concat([df2,df3])

     a    b    c    d
0   12    2   10    4
1   14   16   15    8
2   14    8   16   13
3   18   15   13    9
4   15   13    1    7
0  600  100  500  200
1  700  800  750  400
2  700  400  800  650
3  900  750  650  450
4  750  650   50  350

In [138]:
pd.concat([df2,df3], ignore_index=True)

     a    b    c    d
0   12    2   10    4
1   14   16   15    8
2   14    8   16   13
3   18   15   13    9
4   15   13    1    7
5  600  100  500  200
6  700  800  750  400
7  700  400  800  650
8  900  750  650  450
9  750  650   50  350

In [139]:
df3.columns=["a","b","c","x"]
df3

     a    b    c    x
0  600  100  500  200
1  700  800  750  400
2  700  400  800  650
3  900  750  650  450
4  750  650   50  350

In [140]:
pd.concat([df2,df3])

     a    b    c     d      x
0   12    2   10   4.0    NaN
1   14   16   15   8.0    NaN
2   14    8   16  13.0    NaN
3   18   15   13   9.0    NaN
4   15   13    1   7.0    NaN
0  600  100  500   NaN  200.0
1  700  800  750   NaN  400.0
2  700  400  800   NaN  650.0
3  900  750  650   NaN  450.0
4  750  650   50   NaN  350.0

In [141]:
pd.concat([df2,df3],join="inner")

     a    b    c
0   12    2   10
1   14   16   15
2   14    8   16
3   18   15   13
4   15   13    1
0  600  100  500
1  700  800  750
2  700  400  800
3  900  750  650
4  750  650   50

In [142]:
# merge()

In [143]:
df4= pd.DataFrame({'id': [1, 2, 3, 4, 4], 'skills': ['excel', 'java', 'PHP','excel', "java"]})
df5 = pd.DataFrame({'id': [1, 2, 3, 4], 'name': ['Ali', 'Can', 'Su', 'Ada']})
df6 = pd.DataFrame({'name': ['Ali', 'Can', 'Su' ], 'age': [25, 30, 35,]})

In [144]:
pd.merge(df5,df6, on="name")

   id name  age
0   1  Ali   25
1   2  Can   30
2   3   Su   35

In [145]:
pd.merge(df4,df5)

   id skills name
0   1  excel  Ali
1   2   java  Can
2   3    PHP   Su
3   4  excel  Ada
4   4   java  Ada

In [146]:
# create a dictionary with some different data types as values
new_dict={"name":["aslı","can","deniz"],
          "age": np.array([24,26,25]),
          "weight" : (75,93,89),
          "height" : pd.Series([6,8,5], index=["aslı","can","deniz"]), #df index
          "siblings" : 1,
          "gender" : ["F","M","F"]}

new_df=pd.DataFrame(new_dict)
new_df

        name  age  weight  height  siblings gender
aslı    aslı   24      75       6         1      F
can      can   26      93       8         1      M
deniz  deniz   25      89       5         1      F

In [147]:
new_df["Married"]=False
new_df

        name  age  weight  height  siblings gender  Married
aslı    aslı   24      75       6         1      F    False
can      can   26      93       8         1      M    False
deniz  deniz   25      89       5         1      F    False

In [148]:
# Loading one of the built-in datasets from the Seaborn library.
import seaborn as sns
dfn=sns.load_dataset("diamonds")

In [149]:
dfn.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [150]:
dfn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

In [151]:
np.mean(dfn.select_dtypes(include=[np.number]), axis=0)

carat       0.797940
depth      61.749405
table      57.457184
price    3932.799722
x           5.731157
y           5.734526
z           3.538734
dtype: float64

In [152]:
#groupby
dfn.groupby("cut")

<ipython-input-152-329271c44943>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby("cut")

In [153]:
dfn.groupby("cut")["price"].mean()

<ipython-input-153-9d5c110efe74>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby("cut")["price"].mean()

cut
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Good         3928.864452
Fair         4358.757764
Name: price, dtype: float64

In [154]:
dfn.groupby("color")["price"].mean()

<ipython-input-154-b9a31f3c2ead>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby("color")["price"].mean()

color
D    3169.954096
E    3076.752475
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

In [155]:
dfn.groupby("carat")["price"].describe()

,count,mean,std,min,25%,50%,75%,max
carat,,,,,,,,
0.20,12.0,365.166667,6.350853,345.0,367.0,367.0,367.0,367.0
0.21,9.0,380.222222,20.504742,326.0,386.0,386.0,386.0,394.0
0.22,5.0,391.400000,54.532559,337.0,342.0,404.0,404.0,470.0
0.23,293.0,486.143345,70.783966,326.0,438.0,498.0,530.0,688.0
0.24,254.0,505.185039,88.247951,336.0,437.5,491.0,552.0,963.0
...,...,...,...,...,...,...,...,...
4.00,1.0,15984.000000,NaN,15984.0,15984.0,15984.0,15984.0,15984.0
4.01,2.0,15223.000000,0.000000,15223.0,15223.0,15223.0,15223.0,15223.0
4.13,1.0,17329.000000,NaN,17329.0,17329.0,17329.0,17329.0,17329.0
4.50,1.0,18531.000000,NaN,18531.0,18531.0,18531.0,18531.0,18531.0
5.01,1.0,18018.000000,NaN,18018.0,18018.0,18018.0,18018.0,18018.0

In [156]:
#aggregate
dfn.groupby("color")["price"].aggregate([ min, np.mean, np.median, max])

<ipython-input-156-3db396988a78>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby("color")["price"].aggregate([ min, np.mean, np.median, max])
<ipython-input-156-3db396988a78>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  dfn.groupby("color")["price"].aggregate([ min, np.mean, np.median, max])
<ipython-input-156-3db396988a78>:2: FutureWarning: The provided callable <function mean at 0x7fcb4fb620c0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  dfn.groupby("color")["price"].aggregate([ min, np.mean, np.median, max])
<ipython-input-156-3db396988a78>:2: FutureWarning: The provided callable <function median at 0x7fcb4f5a6700> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  dfn.groupby("color")["price"].aggregate([ min, np.mean, np.median, max])
<ipython-input-156-3db396988a78>:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  dfn.groupby("color")["price"].aggregate([ min, np.mean, np.median, max])

       min         mean  median    max
color
D      357  3169.954096  1838.0  18693
E      326  3076.752475  1739.0  18731
F      342  3724.886397  2343.5  18791
G      354  3999.135671  2242.0  18818
H      337  4486.669196  3460.0  18803
I      334  5091.874954  3730.0  18823
J      335  5323.818020  4234.0  18710

In [157]:
dfn.groupby("color").aggregate({"carat": np.mean,"price": np.mean})

<ipython-input-157-5762ee8104fc>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby("color").aggregate({"carat": np.mean,"price": np.mean})
<ipython-input-157-5762ee8104fc>:1: FutureWarning: The provided callable <function mean at 0x7fcb4fb620c0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  dfn.groupby("color").aggregate({"carat": np.mean,"price": np.mean})

          carat        price
color
D      0.657795  3169.954096
E      0.657867  3076.752475
F      0.736538  3724.886397
G      0.771190  3999.135671
H      0.911799  4486.669196
I      1.026927  5091.874954
J      1.162137  5323.818020

In [158]:
#filter
dfn.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [159]:
dfn.filter(items=["carat","price"]).head(10)

   carat  price
0   0.23    326
1   0.21    326
2   0.23    327
3   0.29    334
4   0.31    335
5   0.24    336
6   0.24    336
7   0.26    337
8   0.22    337
9   0.23    338

In [160]:
dfn_filtered = dfn.groupby("cut").filter(lambda x: (x["x"].mean() > dfn["x"].mean()) &
                                                   (x["y"].mean() > dfn["y"].mean()) &
                                                   (x["z"].mean() > dfn["z"].mean()))
result = dfn_filtered.groupby("cut")["price"].mean()
print(result)

<ipython-input-160-87d0b1fd80b8>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn_filtered = dfn.groupby("cut").filter(lambda x: (x["x"].mean() > dfn["x"].mean()) &

cut
Ideal                NaN
Premium      4584.257704
Very Good    3981.759891
Good         3928.864452
Fair         4358.757764
Name: price, dtype: float64

<ipython-input-160-87d0b1fd80b8>:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = dfn_filtered.groupby("cut")["price"].mean()

In [161]:
dfn_filtered2 = dfn.groupby("color").filter(lambda x: x["price"].mean() > 1000)

print(dfn_filtered2.groupby("color")["price"].mean())

color
D    3169.954096
E    3076.752475
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

<ipython-input-161-a8154cdb6623>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn_filtered2 = dfn.groupby("color").filter(lambda x: x["price"].mean() > 1000)
<ipython-input-161-a8154cdb6623>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(dfn_filtered2.groupby("color")["price"].mean())

In [162]:
#transform

In [163]:
dfn_mean=dfn.groupby("cut")["price"].transform("mean")
dfn_mean

<ipython-input-163-76bf866692f2>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn_mean=dfn.groupby("cut")["price"].transform("mean")

0        3457.541970
1        4584.257704
2        3928.864452
3        4584.257704
4        3928.864452
            ...
53935    3457.541970
53936    3928.864452
53937    3981.759891
53938    4584.257704
53939    3457.541970
Name: price, Length: 53940, dtype: float64

In [164]:
#apply

In [165]:
dfn.groupby("cut")["price"].apply(np.mean)

<ipython-input-165-e08cc09a8b68>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby("cut")["price"].apply(np.mean)

cut
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Good         3928.864452
Fair         4358.757764
Name: price, dtype: float64

In [166]:
#pivot table

In [167]:
dfn.groupby(["cut","color"])[["price"]].aggregate("mean").unstack()
# If double square brackets are added, it transforms into a DataFrame form.
# unstack(): "It is a function that converts one of the row indexes of a multi-level DataFrame into columns.

<ipython-input-167-8c45b1af0210>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfn.groupby(["cut","color"])[["price"]].aggregate("mean").unstack()

                 price                                                      \
color                D            E            F            G            H
cut
Ideal      2629.094566  2597.550090  3374.939362  3720.706388  3889.334831
Premium    3631.292576  3538.914420  4324.890176  4500.742134  5216.706780
Very Good  3470.467284  3214.652083  3778.820240  3872.753806  4535.390351
Good       3405.382175  3423.644159  3495.750275  4123.482204  4276.254986
Fair       4291.061350  3682.312500  3827.003205  4239.254777  5135.683168


color                I            J
cut
Ideal      4451.970377  4918.186384
Premium    5946.180672  6294.591584
Very Good  5255.879568  5103.513274
Good       5078.532567  4574.172638
Fair       4685.445714  4975.655462

In [168]:
dfn.pivot_table("price", index="cut", columns="color")
# A simpler version of the previous code using a pivot table."

<ipython-input-168-ae27863a54a8>:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  dfn.pivot_table("price", index="cut", columns="color")

color,D,E,F,G,H,I,J
cut,,,,,,,
Ideal,2629.094566,2597.550090,3374.939362,3720.706388,3889.334831,4451.970377,4918.186384
Premium,3631.292576,3538.914420,4324.890176,4500.742134,5216.706780,5946.180672,6294.591584
Very Good,3470.467284,3214.652083,3778.820240,3872.753806,4535.390351,5255.879568,5103.513274
Good,3405.382175,3423.644159,3495.750275,4123.482204,4276.254986,5078.532567,4574.172638
Fair,4291.061350,3682.312500,3827.003205,4239.254777,5135.683168,4685.445714,4975.655462

In [169]:
dfn.carat.describe()

count    53940.000000
mean         0.797940
std          0.474011
min          0.200000
25%          0.400000
50%          0.700000
75%          1.040000
max          5.010000
Name: carat, dtype: float64

In [170]:
carat_new=pd.cut(dfn["carat"], [0,3,5.01])
carat_new.head()

0    (0.0, 3.0]
1    (0.0, 3.0]
2    (0.0, 3.0]
3    (0.0, 3.0]
4    (0.0, 3.0]
Name: carat, dtype: category
Categories (2, interval[float64, right]): [(0.0, 3.0] < (3.0, 5.01]]

In [171]:
dfn.pivot_table("price",["carat", carat_new],"cut")

<ipython-input-171-d9d2ccab5000>:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  dfn.pivot_table("price",["carat", carat_new],"cut")

cut                     Ideal       Premium     Very Good        Good     Fair
carat carat
0.20  (0.0, 3.0]   367.000000    364.250000    367.000000         NaN      NaN
0.21  (0.0, 3.0]          NaN    379.500000    386.000000         NaN      NaN
0.22  (0.0, 3.0]          NaN    405.000000           NaN         NaN    337.0
0.23  (0.0, 3.0]   498.181818    566.500000    482.690355  442.935484    369.0
0.24  (0.0, 3.0]   555.028986    559.882353    481.090909  458.142857      NaN
...                       ...           ...           ...         ...      ...
4.00  (3.0, 5.01]         NaN           NaN  15984.000000         NaN      NaN
4.01  (3.0, 5.01]         NaN  15223.000000           NaN         NaN      NaN
4.13  (3.0, 5.01]         NaN           NaN           NaN         NaN  17329.0
4.50  (3.0, 5.01]         NaN           NaN           NaN         NaN  18531.0
5.01  (3.0, 5.01]         NaN           NaN           NaN         NaN  18018.0

[273 rows x 5 columns]